### ISSUE TITLE
Get bare-bones service running

### ISSUE THREAD

**Issue by sjy252** [stern-devops-2020-products/products#12]
**As a** developer
**I need** the bare-bones service able to run
**So that** I can add functionality and test cases

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
When I use the command flask run -h 0.0.0.0
Then the service should start
and when nosetests is run
then the tests should start and run
```

**Comment by sjy252** [comment]
Backlog grooming notes:

Team is uncertain what this entails, but knows it's necessary

**Comment by Kjabraham** [comment]
Updated this story to reflect what needs to happen. I will go ahead and take this so then we can take the different CRUD functions and get those going
