### ISSUE TITLE
Connect TravisCI

### ISSUE THREAD

**Issue by Kjabraham** [stern-devops-2020-products/products#27]
**As a** developer
**I need** TravisCI integrated
**So that** tests are run when I try and push a build

**Assumptions:** 
* nosetests are set up to run

**Acceptance Criteria:**
```
When I create a pull request
Then TravisCI should run nosetests before it can be merged
```

**Comment by eleanor-mcneil** [comment]
@sjy252 I just noticed this in the new issues when looking at the board - you mentioned in Slack that you connected Travis CI already?

**Comment by Kjabraham** [comment]
Not yet. I needed Scott to do something and I haven't had a chance to go back and do it

**Comment by eleanor-mcneil** [comment]
Ah ok got it thanks! Missed that somehow...
